window.OMS = window.OMS || {};

(() => {
  const OMS = window.OMS;

  OMS.refs = {
    canvas: document.getElementById('canvas'),
    noiseCanvas: document.getElementById('noise'),
    waveCanvas: document.getElementById('wave-canvas'),
    noiseGrid: document.getElementById('noise-grid'),
    escapeBtn: document.getElementById('escape-btn'),
    statusLine: document.getElementById('status-line'),
    countdown: document.getElementById('countdown'),
    visitorId: document.getElementById('visitor-id'),
    phase4: document.getElementById('phase4'),
    phaseCat: document.getElementById('phase-cat'),
    tooltip: document.getElementById('tooltip'),
    progressTop: document.getElementById('progress-top'),
    waveform: document.getElementById('waveform'),
    sessionTime: document.getElementById('session-time'),
    coords: document.getElementById('coords'),
    idleMsg: document.getElementById('idle-msg'),
    catAscii: document.getElementById('cat-ascii'),
    catTimer: document.getElementById('cat-timer'),
    globalPresence: document.getElementById('global-presence'),
    presenceCounter: document.getElementById('presence-counter'),
    glitchOverlay: document.getElementById('glitch-overlay'),
    volWrap: document.getElementById('vol-wrap'),
    volSlider: document.getElementById('vol-slider'),
    muteBtn: document.getElementById('mute-btn'),
    pwaBanner: document.getElementById('pwa-banner'),
    pwaInstallBtn: document.getElementById('pwa-install-btn'),
    visitBadge: document.getElementById('visit-badge'),
    introOverlay: document.getElementById('intro-overlay'),
    introStartBtn: document.getElementById('intro-start-btn'),
    emergencyExit: document.getElementById('emergency-exit'),
    emergencyDesktop: document.getElementById('ee-desktop'),
    emergencyTint: document.getElementById('ee-tint'),
    mobileTutorial: document.getElementById('mobile-tutorial'),
    tutorialText: document.getElementById('tut-text'),
    tutorialButton: document.getElementById('tut-btn'),
    wtfMsg: document.getElementById('wtf-msg'),
    secretCounter: document.getElementById('secret-counter'),
    backpackBtn: document.getElementById('backpack-btn'),
    backpackModal: document.getElementById('backpack-modal'),
    backpackGrid: document.getElementById('backpack-grid'),
    backpackProgress: document.getElementById('backpack-progress'),
    backpackClose: document.getElementById('backpack-close'),
    inagentOverlay: document.getElementById('inagent-overlay'),
    inagentCanvas: document.getElementById('inagent-canvas'),
    inagentStartScreen: document.getElementById('inagent-start-screen'),
    inagentStartBtn: document.getElementById('inagent-start-btn'),
    inagentEndScreen: document.getElementById('inagent-end-screen'),
    inagentEndTitle: document.getElementById('inagent-end-title'),
    inagentEndMoves: document.getElementById('inagent-end-moves'),
    inagentRestartBtn: document.getElementById('inagent-restart-btn'),
    inagentTransScreen: document.getElementById('inagent-transition-screen'),
    inagentTransText: document.getElementById('inagent-transition-text'),
    inagentHudSector: document.getElementById('inagent-hud-sector'),
    inagentHudMoves: document.getElementById('inagent-hud-moves'),
    inagentHudState: document.getElementById('inagent-hud-plans'),
    inagentMsg: document.getElementById('inagent-msg'),
    inagentCloseBtn: document.getElementById('inagent-close'),
  };

  OMS.constants = {
    TOTAL_NEEDED_SECONDS: 86400,
    LIFETIME_LIMIT_SECONDS: 1000000,
    GRID_COUNT: 100,
    SESSION_LIMIT_SECONDS: 900,
    DAY_SECONDS: 86400,
    SOUND_MODES: ['underwater', 'forest', 'space', 'machine', 'dream', 'void'],
    SOUND_NAMES: {
      underwater: 'ПОДВОДНЫЙ',
      forest: 'ЛЕСНОЙ',
      space: 'КОСМОС',
      machine: 'МЕХАНИКА',
      dream: 'СОН',
      void: 'ПУСТОТА',
    },
    LOCATIONS: [
      'BALI', 'TOKYO', 'OSLO', 'NYC', 'CAIRO', 'DUBAI', 'SEOUL', 'LONDON', 'RIO', 'MUMBAI',
      'LA', 'PARIS', 'BEIJING', 'SYD', 'BERLIN', 'MIAMI', 'DUBAI', 'REYKJAVIK', 'PRAGUE', 'LIMA',
      'LAGOS', 'OSAKA', 'MOSCOW', 'ZURICH', 'BOSTON', 'SINGAS', 'ISTANBUL', 'JAKARTA', 'MANILA', 'LVIV',
      'HANOI', 'ACCRA', 'NAIROBI', 'BRUSSELS', 'WIEN', 'ROME', 'ATHENS', 'LIMA', 'BOGOTA', 'DALLAS',
      'HOUSTON', 'PHOENIX', 'DENVER', 'SEATTLE', 'PORTLAND', 'MONTREAL', 'TORONTO', 'BUDAPEST', 'WARSAW', 'RIGA',
      'VILNIUS', 'TALLIN', 'MINSK', 'TBILISI', 'BAKU', 'YEREVAN', 'TASHKENT', 'ALMATY', 'NOVOSIBIRSK', 'YEKATERINBURG',
      'IRKUTSK', 'VLADIVOSTOK', 'MAGADAN', 'MURMANSK', 'ARKHANGELSK', 'SYKTYVKAR', 'ULAN-UDE', 'KYZYL', 'ANADYR', 'PETROPAVL',
      'YAKUTSK', 'KHABAROVSK', 'SAKHALIN', 'KAMCHATKA', 'CHUKOTKA', 'KRASNOYARSK', 'TOMSK', 'TYUMEN', 'OMSK', 'CHELYABINSK',
      'ULYANOVSK', 'VORONEZH', 'PERM', 'SAMARA', 'KAZAN', 'NIZHNY', 'SARATOV', 'VOLGOGRAD', 'KRASNODAR', 'ROSTOV',
      'STAVROPOL', 'MAHACHKALA', 'SOCHI', 'SIMFEROPOL', 'SEVASTOPOL', 'ODESSA', 'KHARKIV', 'DNIPRO', 'DONETSK', 'ZAPORIZHZHYA'
    ],
    KONAMI: ['ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight', 'b', 'a'],
    BAN_REASON_KEY: 'oms_ban_reason',
    PENDING_FORBIDDEN_SECRET_KEY: 'oms_pending_forbidden_secret',
    SECRET_STORAGE_KEY: 'oms_secrets_v1',
    LIFETIME_SECONDS_KEY: 'oms_lifetime_seconds_v1',
    SECRET_DEFS: [
      {
        id: 'entry_signal',
        title: 'ПЕРВЫЙ СИГНАЛ',
        hint: 'Сделай первый шаг в сеанс.',
        description: 'Ты вошел в основной цикл сайта.',
        category: 'achievement',
      },
      {
        id: 'first_cell',
        title: 'ПЕРВЫЙ КАНАЛ',
        hint: 'Открой любую ячейку.',
        description: 'Открыта первая ячейка в сетке шумов.',
        category: 'achievement',
      },
      {
        id: 'forbidden_button',
        title: 'ЗАПРЕТНЫЙ КЛИК',
        hint: 'Запрет сработает только после полной ловушки.',
        description: 'Ты прошел бан и подтвердил личность после запретной кнопки.',
        category: 'achievement',
      },
      {
        id: 'casino',
        title: 'ПАРА-КЛУБ',
        hint: 'Спонсор реагирует на двойной клик.',
        description: 'Открыта интерактивная казино-вставка спонсора.',
        category: 'interactive',
        action: 'casino',
      },
      {
        id: 'sponsor_snake',
        title: 'ЗМЕЯ СПОНСОРА',
        hint: 'В секретном режиме стрелки работают наоборот.',
        description: 'Секрет засчитан только после 15 добычи в странной змейке со стрелками и WASD.',
        category: 'achievement',
      },
      {
        id: 'inagent',
        title: 'ИНАГЕНТ',
        hint: 'Клавиша B иногда открывает не букву, а проход.',
        description: 'Открыт скрытый режим проникновения CASTLE.EXE с охраной, планами и выходом.',
        category: 'interactive',
        action: 'inagent',
      },
      {
        id: 'godzilla',
        title: 'TOKYO INCIDENT',
        hint: 'Одна из локаций реагирует на навязчивость.',
        description: 'Событие с TOKYO было активировано.',
        category: 'achievement',
      },
      {
        id: 'emergency_exit',
        title: 'EMERGENCY EXIT',
        hint: 'Проверь системные горячие клавиши.',
        description: 'Открыт режим экстренного экрана.',
        category: 'achievement',
      },
      {
        id: 'double_space',
        title: 'ПЕРЕВОРОТ',
        hint: 'Один и тот же символ иногда слушают дважды.',
        description: 'Двойной пробел перевернул весь интерфейс.',
        category: 'achievement',
      },
      {
        id: 'ebat_b',
        title: 'СИГНАЛ B',
        hint: 'После входа цепочка не заканчивается сразу.',
        description: 'Вторая буква скрытой цепочки сработала.',
        category: 'achievement',
      },
      {
        id: 'ebat_a',
        title: 'СИГНАЛ A',
        hint: 'У последовательности есть середина.',
        description: 'Третья буква скрытой цепочки принята.',
        category: 'achievement',
      },
      {
        id: 'ebat_t',
        title: 'СИГНАЛ T',
        hint: 'Некоторые маршруты читаются только до конца.',
        description: 'Полная скрытая цепочка E-B-A-T завершена.',
        category: 'achievement',
      },
      {
        id: 'konami',
        title: 'KONAMI TRACE',
        hint: 'Старый код иногда работает.',
        description: 'Введен классический Konami-код.',
        category: 'achievement',
      },
      {
        id: 'cat_revelation',
        title: 'КОШАЧИЙ ЦИКЛ',
        hint: 'Сеанс когда-нибудь заканчивается.',
        description: 'Достигнута финальная кошачья фаза.',
        category: 'achievement',
      },
      {
        id: 'console_access',
        title: 'ТЕНЕВАЯ КОНСОЛЬ',
        hint: 'Некоторые символы открывают сервисный слой.',
        description: 'Открыта скрытая консоль наблюдения.',
        category: 'interactive',
        action: 'console',
      },
    ],
  };

  OMS.state = {
    currentPhase: 0,
    mouseX: 0,
    mouseY: 0,
    mouseVel: 0,
    smoothSpeed: 0,
    lastMX: 0,
    lastMY: 0,
    totalMouseDist: 0,
    sessionSeconds: 0,
    countdownSec: OMS.constants.DAY_SECONDS - 1,
    exploded: false,
    btnX: window.innerWidth / 2,
    btnY: window.innerHeight / 2,
    catchCount: 0,
    activeCells: new Set(),
    seenPct: 2,
    activeSeconds: 0,
    catNextSec: OMS.constants.DAY_SECONDS,
    catInterval: null,
    currentVolume: 0.4,
    isMuted: false,
    isMobile: ('ontouchstart' in window) || (navigator.maxTouchPoints > 0),
    deferredPrompt: null,
    userCity: '',
    idleShowing: false,
    lastActivity: Date.now(),
    ebtState: '',
    konamiIdx: 0,
    typedBuffer: '',
    typedTimer: null,
    flipped: false,
    lastSpace: 0,
    sponsorGridX: 2,
    sponsorGridY: 4,
    casinoShown: false,
    tokyoClicks: 0,
    godzillaShown: false,
    eeActive: false,
    eeTotalDist: 0,
    rafId: 0,
    startTs: 0,
    lastRandGlitch: 0,
    cellClickCount: 0,
    introAccepted: false,
    statusHoldUntil: 0,
    secretProgress: {},
    unlockedSecrets: new Set(),
    newSecretCount: 0,
    pendingForbiddenSecret: false,
    lastBanReason: 'generic',
    banTick: null,
    noiseActionCount: 0,
    sessionLimitTriggered: false,
    lastControlJoltAt: 0,
    lifetimeBaseSeconds: 0,
    lifetimeSeconds: 0,
    lifetimeLimitReached: false,
    sponsorQuest: {
      active: false,
      ready: false,
      score: 0,
      targetScore: 15,
      food: { x: 7, y: 2 },
      objective: { x: 7, y: 2 },
      snakeTail: [],
      directionX: 1,
      directionY: 0,
      intentX: 1,
      intentY: 0,
      tickTimer: null,
      startTimer: null,
      completeTimer: null,
      statusTimer: null,
      paused: false,
      speedMs: 320,
      lastTapAt: 0,
    },
    inagent: {
      open: false,
      state: 'intro',
      level: 0,
      player: { r: 1, c: 1 },
      guards: [],
      guardHistory: [],
      hasPlans: false,
      moves: 0,
      flashMsg: '',
      flashTimer: 0,
      openDoors: [],
      doorTimer: 0,
      decoyTarget: null,
      rewindCharges: 0,
      rewindCollected: false,
      transitionTimer: null,
    },
    secretSystems: {
      controlPower: 0,
      worldPower: 0,
      riskPower: 0,
      metaXp: 0,
      imprints: {},
      control: {
        phaseEntryDistance: 300,
        fleeDistance: 160,
        invertChance: 0.02,
        arrowStep: 1,
        doubleSpaceWindowMs: 400,
        controlScale: 1,
        buttonSpeedMultiplier: 1,
        invertControls: false,
        shaderSpeedBoost: 1,
        mouseVelocityScale: 1,
      },
      world: {
        phaseDelayMs: 3500,
        glitchBars: 1,
        countdownDrain: 1,
        hueRotate: 0,
        saturate: 1,
        phaseNoiseBoost: 0,
        shaderPhaseOffset: 0,
        glitchIntervalMultiplier: 1,
      },
      risk: {
        banMultiplier: 1,
        jackpotBonus: 0,
        punishmentBias: 0,
        rewardBias: 0,
        sessionLimitScale: 1,
        sessionDrainMultiplier: 1,
        banExtraMs: 0,
        riskDebt: 0,
      },
      meta: {
        level: 1,
        xp: 0,
        relicSlots: 1,
        title: 'INIT',
        presenceMultiplier: 1,
      },
    },
  };

  OMS.audio = {
    ctx: null,
    masterGain: null,
    droneOsc: null,
    droneGain: null,
    noiseSource: null,
    noiseGain: null,
    soundMode: OMS.constants.SOUND_MODES[Math.floor(Math.random() * OMS.constants.SOUND_MODES.length)],
    sponsorMusic: {
      active: false,
      stepTimer: null,
      padOsc: null,
      chordOsc: null,
      bellOsc: null,
      gain: null,
      filter: null,
      stepIndex: 0,
    },
  };

  OMS.render = {
    gl: null,
    width: 0,
    height: 0,
    program: null,
    uniforms: {},
    wavePhase: 0,
  };

  OMS.visit = {
    data: { count: 0, totalSeconds: 0 },
  };

  OMS.api = {};

  OMS.helpers = {
    clamp(value, min, max) {
      return Math.min(max, Math.max(min, value));
    },
    formatTime(sec) {
      const h = Math.floor(sec / 3600).toString().padStart(2, '0');
      const m = Math.floor((sec % 3600) / 60).toString().padStart(2, '0');
      const s = Math.floor(sec % 60).toString().padStart(2, '0');
      return `${h}:${m}:${s}`;
    },
    formatSession(sec) {
      const m = Math.floor(sec / 60).toString().padStart(2, '0');
      const s = Math.floor(sec % 60).toString().padStart(2, '0');
      return `00:${m}:${s}`;
    },
    getSeenPct() {
      const p = OMS.state.activeSeconds / OMS.constants.TOTAL_NEEDED_SECONDS * 100;
      return Math.min(99.9, p);
    },
  };

  OMS.utils = OMS.helpers;
})();
